### PR TITLE
Eman's updates

### PR DESCRIPTION
**Pull request by dolce-emmy**
could you please add my changes to your repositry

### CODE REVIEW

**Review by Mohammedalshameri — APPROVED** [review]

**Review by rbinduc — APPROVED** [review]
great job

**Review by Ludovil — APPROVED** [review]

**Review by Mohammedalshameri — COMMENTED** [review]
The submitted pull requests has been reviewed

**Review by alexpavlyukovets — COMMENTED** [review]
somehow the file doesn't have all the info from other students

**Review by Mohammedalshameri — COMMENTED** [review]
The submitted pull requests has been reviewed

**Pull request merged**
