### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ludovil**
Hi, 

I added my name on the list

### CODE REVIEW

**Review by Mohammedalshameri — APPROVED** [review]

**Review by megravity — APPROVED** [review]

**Review by Mohammedalshameri — APPROVED** [review]

**Review by Mohammedalshameri — APPROVED** [review]

**Review by setazarm — APPROVED** [review]

**Review by Mohammedalshameri — COMMENTED** [review]
The submited Pull Request has been reviewed

**Review by Mohammedalshameri — COMMENTED** [review]
The submitted pull requests has been reviewed

**Review by Mohammedalshameri — COMMENTED** [review]
The submitted pull requests has been reviewed

**Review by Mohammedalshameri — COMMENTED** [review]
The submitted pull requests has been reviewed

**Review by Mohammedalshameri — COMMENTED** [review]
The submitted pull requests has been reviewed

**Pull request merged**
